### ISSUE TITLE
Building with webpack

### ISSUE THREAD

**Issue by theaceofthespade** [giniedp/ammojs-typed#15]
I started my project with parcel to save time, so it ran fine with that, but I've been totally unable to build with webpack5.

Everything else works, and then I get this error when I try to initialize Ammo as so:

```
import AmmoModule from "ammojs-typed";

...

AmmoModule().then((ammo) => {
      AmmoStart(ammo);
    });
```

I've tried different names for the es6 import, I have all the requested TSconfig changes, I've got the webpack fallbacks for fs and path- nothing fixes this issue.

`Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Ammo')
    at ammo.js:978:320
    at LevelBoxes.onLoad (level-boxes.ts:265:19)
(anonymous)	@	ammo.js:978`

Has anyone else run into this issue?  I've been unable to find a way to resolve it and have to just switch back to parcel at this point.

**Comment by theaceofthespade** [comment]
PIBCAP issue (Problem In Between Keyboard And Chair) - after lots of tinkering, I discovered the final fix was removing type="module" from the script tag in the html. 

So if you see this error message, "Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'Ammo') at ammo.js"  apparently one of the things it can mean is "the browser it trying to read it as a module when it shouldn't).  Naturally Parcel didn't care about this because it was using the html file as an entry point, and actually *needed* to look at the js as a module.

Hope my wasted time can help someone else save some!  And thanks @giniedp for all the work on the repo!
